### ISSUE TITLE
AddAutoFallbackTransition?

### ISSUE THREAD

**Issue by prlaba** [scottctr/NStateManager#18]
I attempted to implement your AddAutoFallbackTransition feature, based on the Walk-Run-Jump example you provided but discovered that I couldn't compile your example because none of the four overloaded AddAutoFallbackTransition methods had argument types that matched those in your example.

Do I not have the latest code?  Or did I jump the gun trying out a feature that's still under construction?

Thanks,

Paul

**Comment by scottctr** [comment]
yes, that was a preview, but I'm actually working on those changes right now. :-) 

Hope to have the automatic transitions, new configuration/transition events, and possibly parameterized entry/exit/re-entry actions completed, tested, and released this weekend. I probably won't get the docs updated for these features until next weekend though.

**Comment by scottctr** [comment]
I've posted the latest code that includes [this example](https://github.com/scottctr/NStateManager/blob/master/Tests/NStateManager.Tests/AutoFallbackTest.cs). Just let me know if you find any issues.

**Comment by prlaba** [comment]
Thanks Scott for the quick turnaround!  I'll give these a try.

I have a couple of questions about the AddAutoForwardTransition feature:

1) If the state containing the AddAutoForwardTransition clause includes one or more AddTransition clauses with the same trigger as the AddAutoForwardTransition clause, will the AddAutoForwardTransition clause be checked first? (I assume it would.)

2) If the condition function specified in the AddAutoForwardTransition clause returns false, will the state machine remain in the state containing the AddAutoForwardTransition clause?  (I assume so.)  As such, the state machine will be 'stuck' in that state unless that state includes at least one AddTransition clause to transition to another state.  In your AddAutoForwardTransition example, the boolean function always returns true, but if it were to return false, the state machine would be stuck in the Jumping state.

The same situation exists for the AddAutoFallbackTransition clause, but is not likely a problem; the designer knows that the auto-fallback trigger will ultimately return to same state, so they would already include at least one AddTransition clause in the state's configuration.

Paul

**Comment by prlaba** [comment]
Thanks Scott,

 

Your explanation helped me better understand how the auto-forward feature works and how it might be used.

I had misunderstood, expecting that the AddAutoForwardTransition clause’s condition method would only be called once, at the time the state was initially entered.  Your example helped me realize that I can fire the AddAutoForwardTransition clause’s trigger at any time to have its condition checked again and the transition taken if the condition is true.  That prevents getting ‘stuck’ in a state.  Makes perfect sense now.

Re the auto-fallback feature, I think it would be a problem to land in the temporary state without auto-transitioning back.  Either the condition included in the AddAutoFallbackTransition clause blocks the initial transition to the temporary state, or it doesn’t, in which case the auto-transition back to the initial state should be guaranteed.  I’d recommend not calling the initial condition’s method for the auto-transition back to the initial state, to prevent the scenario where the condition returns true while in the initial state but returns false while in the temporary state.

Paul

**Comment by scottctr** [comment]
> I had misunderstood, expecting that the AddAutoForwardTransition clause’s condition method would only be called once, at the time the state was initially entered.  Your example helped me realize that I can fire the AddAutoForwardTransition clause’s trigger at any time to have its condition checked again and the transition taken if the condition is true.  That prevents getting ‘stuck’ in a state.  Makes perfect sense now.

I fear I've confused you about how auto forwarding works because it is actually only evaluated once. Going back to the example of auto forwarding, let's break it down:
1. Trigger occurs that put's context in NeedsApproval state.
2. The auto forward trigger is evaluated.
2a. If the auto forward trigger's condition met, the context will move to Approved and all is well.
2b. If the auto forward trigger's condition is not met, the context will stay in NeedsApproval. At this point, this context will require a non-auto trigger on the NeedsApproval state to transition out of the NeedsApproval state...otherwise, it will stay in the NeedsApproval state.

Play around with it a bit and just let me know if you find a scenario this doesn't cover.

We're on the same page with the autoFallback condition, but want to put a bit more thought into it before completely removing the condition from the temp state back to the original state. I just hate to remove functionality for a scenario I can't foresee at this time. :-)

Thanks agian for all your feedback!

**Comment by scottctr** [comment]
> The AddAutoForwardTransition configuration method only requires the trigger and toState args (the condition, name and priority args are optional).  But if don’t specify a condition arg, the state machine throws a TypeInitializationException exception (inner exception is ArgumentNullException) at the time its trigger is fired.  Shouldn’t the default for the optional condition arg be _ => true Instead of null?

Definitely a bug, but the bug is that AddAutoForwardTransition should require the condition parameter. Without a condition, it should be configured as a normal transition that goes directly to the forwarded state.

**Comment by prlaba** [comment]
Ok, now that I've put on a few miles playing around with the auto forward feature, let me try to offer my own example that better explains my initial comments.

Consider this simple 3-state state machine for an application-processing workflow:

`WaitingToProcess => WaitingForApproval => Approved`

The state machine defines a single event: `Process`.

Here's the state machine's configuration:

```
var machine = new StateMachine( ... );

machine.ConfigureState(State.WaitingToProcess)
     .AddTransition(trigger: Events.Process, toState: States.WaitingForApproval);

machine.ConfigureState(State.WaitingForApproval)
     .AddAutoForwardTransition(trigger: Events.Process,  toState: States.Approved,
                               condition: CheckApproval)
     .AddTransition(trigger: Events.Process,  toState: States.Approved, condition: CheckApproval);

```
This worked exactly as I had expected/hoped.  Starting in the `WaitingToProcess` state, I fired the `Process` event, which triggered a transition to the `WaitingForApproval` state,  Upon entry to that state, its auto-forward's `CheckApproval` method was immediately called, which returned `false` initially, so no transition to the `Approved` state was taken (the state remained `WaitingForApproval`).  I then fired the `Process` event again, which matched the state's `AddTransition` clause's event, so the `CheckApproval` method was called again, this time returning `true`, so the transition to the `Approved` state was taken.

My point earlier was that, without the `AddTransition` clause in the `WaitForApproval` state's configuration, there would be no way to transition out of that state if the auto-forward transition's condition wasn't met.  (It's not a problem if an auto-forward transition's condition is always met.)

Paul

**Comment by scottctr** [comment]
This makes perfect sense. Thanks for the update!

**Comment by prlaba** [comment]
Hi Scott,

 

At first glance it doesn’t make much sense to define an unconditional auto forwarding transition for a state such that entering the state always results in an immediate exit out of that state.  But …

 

Consider a state machine with the states Off, On and End; and the events TurnOff, TurnOn and TurnOnAF (AF=AutoForward).

 

The Off state configuration has two AddTransition clauses, one with event TurnOn and toState On, the other with event TurnOnAF and toState On.  In other words, there are two distinct transitions from state Off to state On, one via the TurnOn event, the other via the TurnOnAF event.

 

The On state configuration has one AddTransition clause with event TurnOff and toState Off.  It also has an AddAutoForwardTransition clause with event TurnOnAF and toState End.

 

Starting in state Off, if I fire the TurnOn event, the state On is entered, but no auto-forwarding (to state End) occurs, since the transition’s event (TurnOn) doesn’t match the auto-forward’s event (TurnOnAF).  The state remains On until the TurnOff event is fired, causing a transition back to the Off state.

 

Starting again in the state Off, if I instead fire the TurnOnAF event, the On state is entered but then immediately transitions to the End state, since its auto-forward transition’s event (TurnOnAF) matches the Off-to-On transition’s event (TurnOnAF).

 

What does this have to do with making the AddAutoForwardTransition clause’s condition arg optional?  Simply that there may be legitimate reasons for defining a state with an unconditional AddAutoForwardTransition clause, since that state may have other entry transitions that don’t cause the state’s auto-forwarding transition to occur.  The two events that trigger a transition into the On state are effectively the ‘conditions’ that determine if the On state’s auto-forward transition to state End occurs.

 

Even in cases where a state has only a single, unconditional AddAutoForwardTransition clause defined, and all transitions into the state causes the auto-forward transition to occur, a designer may create such a state as a ‘pass-through’ state, using its entry and exit methods to perform actions as a transition passes through the state to the auto-forward state.

 

Given these scenarios, it seems best to me to make the AddAutoForwardTransition clause’s condition argument optional, defaulting to _ => true.

 

Paul

**Comment by scottctr** [comment]
Have you created code for your on/off/end scenario that I could take a look at?

**Comment by prlaba** [comment]
Understood, thanks.
