### ISSUE TITLE
AddAutoForwardTransition should require a condition

### ISSUE THREAD

**Issue by scottctr** [scottctr/NStateManager#22]
> The AddAutoForwardTransition configuration method only requires the trigger and toState args (the condition, name and priority args are optional).  But if don’t specify a condition arg, the state machine throws a TypeInitializationException exception (inner exception is ArgumentNullException) at the time its trigger is fired.

**Comment by scottctr** [comment]
@prlaba Is it possible you had this issue in an older version of the code -- before Sunday's update? I just went to address, but it looks like none of the current AddAutoForward* methods have a default for the condition parameter. 

I ran a few tests and all I could reproduce was the ArgumentNullException when I passed in a null condition (as expected). I haven't been able to reproduce the TypeInitializationException. 

If possible, I'd appreciate a small code sample to reproduce.

**Comment by prlaba** [comment]
Hi Scott,

Hmm…

I created a new ConsoleApp project in VS 2017 and installed the latest NStateManager package via NuGet:

```
PM> Install-Package NStateManager -Version 1.2.1.1

Attempting to gather dependency information for package 'NStateManager.1.2.1.1' with respect to project 'ConsoleApp6', targeting '.NETFramework,Version=v4.7.1'
Gathering dependency information took 281.53 ms
Attempting to resolve dependencies for package 'NStateManager.1.2.1.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'NStateManager.1.2.1.1'
Resolved actions to install package 'NStateManager.1.2.1.1'
Retrieving package 'NStateManager 1.2.1.1' from 'nuget.org'.
Adding package 'NStateManager.1.2.1.1' to folder 'E:\Users\Paul\SkyDrive\.NET Projects\CSharp Projects\Projects\ConsoleApp6\packages'
Added package 'NStateManager.1.2.1.1' to folder 'E:\Users\Paul\SkyDrive\.NET Projects\CSharp Projects\Projects\ConsoleApp6\packages'
Added package 'NStateManager.1.2.1.1' to 'packages.config'
Successfully installed 'NStateManager 1.2.1.1' to ConsoleApp6
Executing nuget actions took 374.16 ms
Time Elapsed: 00:00:00.6690105 Installed correctly.  The AddAutoForwardTransition method shows two overloads:
```

I then created this simple on-off state machine:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NStateManager;

namespace ConsoleApp6
{
  class TestStateMachine
  {
    enum States { On, Off }
    enum Events { TurnOn, TurnOff }

    States State { get; set; } = States.Off;
    StateMachine<TestStateMachine, States, Events> machine;

    public TestStateMachine()
    {
      machine = new StateMachine<TestStateMachine, States, Events>(
                s => s.State, (s, value) => s.State = value);

      machine.ConfigureState(States.Off)
        .AddTransition(Events.TurnOn, States.On);

      machine.ConfigureState(States.On)
        .AddAutoForwardTransition(Events.TurnOff, States.Off) // throws null exception
        .AddEntryAction(_ => Console.WriteLine($"Entering state {State}"))
        .AddExitAction(_ => Console.WriteLine($"Exiting state {State}"));
    }

    public void TestAutoForward()
    {
      machine.FireTrigger(this, Events.TurnOn);
    }
  }

    class Program
  {
    static void Main(string[] args)
    {
      var tsm = new TestStateMachine();
      tsm.TestAutoForward();

      Console.ReadKey();
    }
  }
}
```

Note that the `AddAutoForwardTransition` function includes an `event` arg and `toState` arg but no `condition` arg.

The program compiles without error, but when run throws a null exception error, pointing to the `machine.ConfigureState(States.On)` statement and its clauses.

If you add the condition arg `_ => true` to the `AddAutoForwardTransition` clause and run the program again, it runs successfully.

In looking through the source code, it appears that the two `AddAutoFallBackTransition` functions require the `condition` arg, but the two `AddAutoForwardTransition` functions do not (the `condition` arg defaults to `null`).  

The `condition` arg is also optional (and defaults to `null`) in the two `AddTransition` functions, but they don't cause a null exception to be thrown if not specified.

This code is running on .Net 4.7.1 platform.

Let me know if there's anything else you'd like me to try.

Paul

**Comment by scottctr** [comment]
Thanks Paul! I'll take another look this evening to see what I'm missing.

**Comment by prlaba** [comment]
Glad you found it, thanks for the quick fix.

Paul
