### ISSUE TITLE
StateMachineAsync.FireTriggerAsync<TRequest> throws System.ArgumentException

### ISSUE THREAD

**Issue by CraigRice** [scottctr/NStateManager#25]
**ISSUE:**
`FireTriggerAsync<TRequest>` will not run successfully (the state machine is configured to accept it and then it is invoked with an instance of `TRequest`).

The test below can reproduce the issue.
Currently the error raised is: 

> System.ArgumentException request must be of type Request.

**RESOLUTION:**
The issue can be resolved in `StateConfigurationAsync<T, TState, TTrigger>`

At the method `Task<StateTransitionResult<TState, TTrigger>>` `FireTriggerAsync(ExecutionParameters<T, TTrigger> parameters)`

ExecuteAsync **is called with 'request: null'**, but instead **should be called with 'request: parameters.Request'**.  ExecuteAsync (of the class `FunctionActionParameterized<T, TRequest>`) will compare the type of the provided request instance to the expected `TRequest` and when null is supplied it's never the case, and the `ArgumentException` is raised:

`throw new ArgumentException($"{nameof(request)} must be of type {typeof(TRequest).Name}.");`

**TEST:**

```
        [Fact]
        public async Task FireTriggerAsyncWRequest_withReferenceTypeInstance_triggerExecutes()
        {
            var testRequest = new Request(123.45);

            var sut = new StateMachineAsync<Sale, SaleState, SaleEvent>(
                stateAccessor: sale2 => sale2.State
                , stateMutator: (sale3, newState) => sale3.State = newState);

            sut.ConfigureState(SaleState.Open)
                .AddTriggerAction<Request>(SaleEvent.Pay, async (saleInstance, request, token) =>
                {
                    saleInstance.Balance = request.Value;
                    await Task.Delay(100);
                })
                .AddTransition(SaleEvent.Pay, SaleState.Complete);

            var sale = new Sale(saleID: 45) { State = SaleState.Open };
            var stateTransitionResult = await sut.FireTriggerAsync<Request>(sale, SaleEvent.Pay, testRequest);

            Assert.NotNull(stateTransitionResult);
            Assert.Equal(SaleState.Complete, stateTransitionResult.CurrentState);
            Assert.Equal(SaleState.Complete, sale.State);
            Assert.Equal(sale.Balance, testRequest.Value);
        }

```
And the request is defined as:

```
    public sealed class Request
    {
        public double Value { get; }
        public Request(double value)
        {
            Value = value;
        }
    }
```

**Comment by scottctr** [comment]
Thanks Craig!

**Comment by CraigRice** [comment]
You're welcome. If you have time to roll out a nuget package update this would be very helpful to get it into our project. :)

**Comment by scottctr** [comment]
[Done](https://www.nuget.org/packages/NStateManager/1.2.3)

I'd be interested to hear how you're using this library.
