### ISSUE TITLE
AddTransition<Request> never runs when triggered in async StateMachine.

### ISSUE THREAD

**Issue by CraigRice** [scottctr/NStateManager#28]
`AddTransition<Request>` never runs when triggered in async StateMachine.
The transition is registered ultimately with an instance of `StateTransitionAutoFallbackParameterizedAsync`.  When its method `ExecuteAsync` is called from `StateConfigurationAsync.FireTriggerPrimAsync()` the second optional parameter is not supplied and becomes null.  The check to execute the condition delegate does not execute (thus the problem) as the check requires `currentResult != null`.

A way to get the tests passing is to make the condition:

> currentResult == null ||

 rather than:

> currentResult != null &&

but this would ignore the importance of the check, and maybe its better to properly supply the  second parameter currentResult from the caller.

Tests below show the issue - the synchronous state machine works ok in this scenario and its corresponding tests are available from my current pull request.

```
        [Fact]
        public async Task FireTriggerAsyncWRequest_addTransitionSignatureWRequest_transitionExecutesWithRequestInstance()
        {
            var testRequest = new TestRequest(123.45);

            var sut = new StateMachineAsync<Sale, SaleState, SaleEvent>(
                stateAccessor: sale2 => sale2.State
                , stateMutator: (sale3, newState) => sale3.State = newState);

            var result = default(double);

            sut.ConfigureState(SaleState.Open)
                .AddTransition<TestRequest>(SaleEvent.Pay, SaleState.Complete, (saleInstance, request, token) =>
                {
                    result = request.Value;
                    return Task.FromResult(true);
                });

            var sale = new Sale(saleID: 45) { State = SaleState.Open };
            var stateTransitionResult = await sut.FireTriggerAsync<TestRequest>(sale, SaleEvent.Pay, testRequest);

            Assert.NotNull(stateTransitionResult);
            Assert.Equal(SaleState.Complete, stateTransitionResult.CurrentState);
            Assert.Equal(SaleState.Complete, sale.State);
            Assert.Equal(result, testRequest.Value);
        }

        [Fact]
        public async Task FireTriggerAsyncWRequest_addConsecutiveTransitionSignaturesWRequest_transitionExecutesWithRequestInstance()
        {
            var sut = new StateMachineAsync<Sale, SaleState, SaleEvent>(
                stateAccessor: sale2 => sale2.State
                , stateMutator: (sale3, newState) => sale3.State = newState);

            var result1 = default(double);
            var result2 = default(double);
            var testRequest1 = new TestRequest(123.45);
            var testRequest2 = new TestRequest(12);

            sut.ConfigureState(SaleState.Open)
                .AddTransition<TestRequest>(SaleEvent.Pay, SaleState.ChangeDue, (saleInstance, request, token) =>
                {
                    result1 = request.Value;
                    return Task.FromResult(true);
                });

            sut.ConfigureState(SaleState.ChangeDue)
	            .AddTransition<TestRequest>(SaleEvent.ChangeGiven, SaleState.Complete, (saleInstance, request, token) =>
	            {
		            result2 = request.Value;
		            return Task.FromResult(true);
	            });
			var sale = new Sale(saleID: 45) { State = SaleState.Open };
            await sut.FireTriggerAsync<TestRequest>(sale, SaleEvent.Pay, testRequest1);
            var stateTransitionResult = await sut.FireTriggerAsync<TestRequest>(sale, SaleEvent.ChangeGiven, testRequest2);

            Assert.NotNull(stateTransitionResult);
            Assert.Equal(SaleState.Complete, stateTransitionResult.CurrentState);
            Assert.Equal(SaleState.Complete, sale.State);
            Assert.Equal(result1, testRequest1.Value);
            Assert.Equal(result2, testRequest2.Value);
        }
```

**Comment by CraigRice** [comment]
Example: https://github.com/CraigRice/NStateManager/commit/60e498107e3faf30410452342fd63479a59eac16

**Comment by scottctr** [comment]
Give me a few days to put more thought into this. I'm not yet seeing why it's working in the sync version, but not the async version. One of my goals has been to keep the sync and async versions as close as possible so I'm reluctant to add any deviations in the logic without fully understanding why it's needed.

**Comment by scottctr** [comment]
I just figured this one out. In `StateConfigurationAsync.AddTransition<TRequest>(TTrigger trigger
            , TState toState
            , Func<T, TRequest, CancellationToken, Task<bool>> conditionAsync
            , string name = null
            , uint priority = 1)`
I was calling `StateTransitionFactory<T, TState, TTrigger>.GetStateTransition` with the wrong set of parameters so it was creating an `StateTransitionAutoFallbackParameterizedAsync` instead of `StateTransitionParameterizedAsync`.

I'll wrap up the changes and roll out a new build shortly.

**Comment by scottctr** [comment]
Done. Should be published to nuget shortly.

It's been fun getting back into this project, so just let me know if you find any other issues or have any questions.

**Comment by CraigRice** [comment]
Will do, thanks for fixing them up too.
